"""Cross-artifact substitutions that remain valid observation packages."""
from copy import deepcopy
from fractions import Fraction
import hashlib
import io
import json
from pathlib import Path
import struct
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

from tools import perception_binding as binding
from tools.perception_decision import contract as decision, nuscenes
from tools.perception_observation import formats, package
from tests.test_perception_observation import fixture, read, replace, rebind_window, tree
from tests.test_perception_reference import inputs, xy
from tests.test_perception_windows import identity_file


def prepare(root):
    observation = fixture(root)
    windows = read(observation['window_report'])
    catalog_spec = windows['inputs']['catalog']
    catalog = read(catalog_spec)
    source_hashes = {'clock': catalog['sources']['metadata']['sha256']}
    # Small, actual source-byte identities; normalized rows are independently
    # generated by the established adapter, not assembled by the binding checker.
    for role, offset in [('base', 0), ('camera', 3)]:
        rows = [{'sample_token': w['sample_token'], 'detection_name': 'car', 'detection_score': 1,
                 'translation': [10+offset, 20, 0]} for w in catalog['anchors']]
        spec = identity_file(root/(role+'.json'), decision.encoded(rows))
        catalog['sources'][role] = spec | {'state': 'observed'}
        source_hashes[role] = spec['sha256']
    for row in catalog['anchors']:
        row['nominal_ego_xy'] = {'state': 'observed', 'timestamp_us': row['anchor_timestamp_us'], 'value': xy(10, 20)}
    catalog_spec = identity_file(Path(catalog_spec['path']), decision.encoded(catalog))
    windows['inputs']['catalog'] = catalog_spec
    rebind_window(observation, windows)
    geometry = read(observation['geometry_report']); geometry['inputs']['catalog'] = catalog_spec
    replace(observation, 'geometry_report', geometry)
    case = inputs(2)[1]; case['anchors'] = []; normalizations = []
    for w in windows['windows']:
        sample = w['sample_token']
        anchor, normalization = nuscenes.normalize_frame(
            sample_token=sample, anchor_id=w['anchor_id'], ego_xy=[10, 20], weight=Fraction(1, 2),
            base={'state': 'observed', 'value': [r for r in read(catalog['sources']['base']) if r['sample_token'] == sample]},
            camera={'state': 'observed', 'value': [r for r in read(catalog['sources']['camera']) if r['sample_token'] == sample]},
            source_sha256=source_hashes)
        case['anchors'].append(anchor); normalizations.append(normalization)
    request = {'artifact_id': 'reiyah.perception-binding.request', 'version': '0.1.0',
               'comparison': identity_file(root/'comparison.json', decision.encoded(case)),
               'normalizations': identity_file(root/'normalizations.json', decision.encoded(normalizations)),
               'catalog': catalog_spec}
    return observation, request


class BindingTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(); self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name)
        self.observation, self.request = prepare(self.root)
        self.serial = 0

    def package(self):
        self.serial += 1
        self.out = self.root/f'package-{self.serial}'
        custody = self.root/f'custody-{self.serial}.json'
        result = package.build(self.observation, self.out, custody)
        self.request['observation_custody'] = identity_file(custody, custody.read_bytes())
        self.request['package'] = {'path': str(self.out), 'seal_sha256': result['seal_sha256']}
        return result

    def rejected(self, code, fn=None):
        with self.assertRaises(decision.Invalid) as caught:
            (fn or (lambda: binding.build(self.request)))()
        self.assertEqual(caught.exception.code, code)

    def reseal(self, manifest):
        # Rebuild both the package seal and custody as a plausible substitution.
        # The original inventory and source reports retain their selected bytes.
        data = decision.encoded(manifest); (self.out/'manifest.json').write_bytes(data)
        seal = json.loads((self.out/'SEAL.json').read_bytes())
        seal['manifest'] = package.descriptor('manifest.json', data)
        raw = decision.encoded(seal); (self.out/'SEAL.json').write_bytes(raw)
        sha = hashlib.sha256(raw).hexdigest(); self.request['package']['seal_sha256'] = sha
        custody = read(self.request['observation_custody']); custody['expected_seal_sha256'] = sha
        for row, evidence in zip(custody['captures'], manifest['captures']):
            row['disclosed_evidence'] = evidence['evidence']
        custody['summary'] = package.contract.validate(manifest)
        replace(self.request, 'observation_custody', custody)
        self.assertTrue(package.verify(self.out, sha)['disclosure_verified'])

    def test_exact_population_assets_and_deterministic_report_without_claim_promotion(self):
        self.package(); before = tree(self.out)
        report = binding.build(self.request)
        self.assertEqual(report['windows'], [
            {'window_id': 'window-0001', 'anchor_id': 'one', 'sample_token': 'f0-2',
             'scene_token': 's0', 'anchor_timestamp_us': 3_000_000},
            {'window_id': 'window-0002', 'anchor_id': 'two', 'sample_token': 'f1-2',
             'scene_token': 's1', 'anchor_timestamp_us': 13_000_000}])
        self.assertEqual(report['summary']['evidence_states'], {'delivered': 70})
        self.assertTrue(all(r['source_content_check'] == 'matched' for r in report['captures']))
        for r in report['captures']:
            # Direct original-file comparison, without projection or PLY helpers.
            original = (self.root/'raw'/r['source']['filename']).read_bytes()
            self.assertEqual(r['delivered_source_body'], {'byte_size': len(original),
                             'sha256': hashlib.sha256(original).hexdigest()})
        self.assertEqual(decision.encoded(report), decision.encoded(binding.build(self.request)))
        self.assertFalse(report['reference_constraints_admitted']); self.assertFalse(report['decision_evaluated'])
        self.assertEqual(report['physical_reference_coverage'], 'not_established')
        self.assertEqual(report['human_review'], 'not_established'); self.assertFalse(report['study_selection_performed'])
        self.assertEqual(tree(self.out), before)

    def test_wrong_valid_package_anchor_rejected(self):
        w = read(self.observation['window_report']); w['windows'][0]['anchor_id'] = 'different-anchor'
        rebind_window(self.observation, w)
        g = read(self.observation['geometry_report']); g['windows'][0]['anchor_id'] = 'different-anchor'
        replace(self.observation, 'geometry_report', g)
        result = self.package()
        self.assertTrue(package.verify(self.out, result['seal_sha256'])['disclosure_verified'])
        self.rejected('BINDING_POPULATION')

    def test_same_anchor_different_sample_or_scene_rejected(self):
        for defect in ('sample', 'scene'):
            with self.subTest(defect=defect):
                w = read(self.observation['window_report']); g = read(self.observation['geometry_report'])
                if defect == 'sample':
                    w['windows'][0]['sample_token'] = g['windows'][0]['sample_token'] = 'f0-3'
                else:
                    w['windows'][0]['sample_token'] = g['windows'][0]['sample_token'] = 'f0-2'
                    w['windows'][0]['scene_token'] = 's1'
                replace(self.observation, 'window_report', w)
                g['inputs']['window_report'] = self.observation['window_report']
                replace(self.observation, 'geometry_report', g)
                self.package(); self.rejected('BINDING_POPULATION')

    def test_identical_neutral_package_at_shifted_absolute_clock_is_rejected(self):
        self.package(); original = tree(self.out)
        w = read(self.observation['window_report']); g = read(self.observation['geometry_report'])
        for report in (w, g):
            for window in report['windows']:
                window['anchor_timestamp_us'] += 1
                window['context_window_us'] = [t+1 for t in window['context_window_us']]
        for window in w['windows']:
            for group in window['channels'].values():
                for capture in group['captures']: capture['capture_timestamp_us'] += 1
        for capture in g['captures'].values(): capture['capture_timestamp_us'] += 1
        replace(self.observation, 'window_report', w)
        g['inputs']['window_report'] = self.observation['window_report']
        replace(self.observation, 'geometry_report', g)
        self.package(); self.assertEqual(tree(self.out), original)
        self.rejected('BINDING_POPULATION')

    def test_catalog_and_metadata_identity_changes_rejected(self):
        original_w = read(self.observation['window_report']); original_g = read(self.observation['geometry_report'])
        for report_role, source_role, field, value in [
                ('window_report', 'catalog', 'sha256', 'f'*64),
                ('geometry_report', 'catalog', 'byte_size', 1),
                ('window_report', 'metadata', 'sha256', 'e'*64),
                ('geometry_report', 'metadata', 'byte_size', True)]:
            with self.subTest(report=report_role, source=source_role, field=field):
                w, g = deepcopy(original_w), deepcopy(original_g)
                (w if report_role == 'window_report' else g)['inputs'][source_role][field] = value
                replace(self.observation, 'window_report', w); g['inputs']['window_report'] = self.observation['window_report']
                replace(self.observation, 'geometry_report', g)
                self.package(); self.rejected('BINDING_SOURCE')

    def test_new_catalog_with_same_sample_names_is_not_the_bound_catalog(self):
        self.package(); cat = read(self.request['catalog']); cat['sources']['metadata']['sha256'] = 'a'*64
        replace(self.request, 'catalog', cat); self.rejected('BINDING_SOURCE')

    def test_consistently_forged_negative_metadata_size_is_not_a_source_identity(self):
        cat = read(self.request['catalog']); cat['sources']['metadata']['byte_size'] = -1
        replace(self.request, 'catalog', cat)
        w = read(self.observation['window_report']); g = read(self.observation['geometry_report'])
        for report in (w, g):
            report['inputs']['metadata']['byte_size'] = -1
            report['inputs']['catalog'] = self.request['catalog']
        replace(self.observation, 'window_report', w); g['inputs']['window_report'] = self.observation['window_report']
        replace(self.observation, 'geometry_report', g)
        self.package(); self.rejected('BINDING_SOURCE')

    def test_resealed_valid_substitute_jpeg_and_lidar_rejected_against_original_inventory(self):
        for channel in ('CAM_FRONT', 'LIDAR_TOP'):
            with self.subTest(channel=channel):
                self.package(); m = json.loads((self.out/'manifest.json').read_bytes())
                record = next(r for r in m['captures'] if r['channel'] == channel)
                if channel == 'LIDAR_TOP':
                    data, count = formats.lidar(struct.pack('<10f', 9, 8, 7, 6, 5, 4, 3, 2, 1, 0))
                    record['evidence']['point_count'] = count
                else:
                    from PIL import Image
                    buffer = io.BytesIO(); Image.new('RGB', (4, 3), (200, 100, 50)).save(buffer, format='JPEG')
                    data = buffer.getvalue()
                asset = record['evidence']['asset']; (self.out/asset['filename']).write_bytes(data)
                record['evidence']['asset'] = package.descriptor(asset['filename'], data)
                self.reseal(m); self.rejected('BINDING_ASSET')

    def test_valid_resealed_neutral_geometry_substitution_rejected(self):
        self.package(); m = json.loads((self.out/'manifest.json').read_bytes())
        m['windows'][0]['channels']['LIDAR_TOP']['captures'][0]['sensor_to_anchor_ego']['matrix'][0][3] = decision.wire(Fraction(999))
        self.reseal(m); self.rejected('BINDING_PROJECTION')

    def test_omitted_extra_and_duplicate_comparison_anchors_are_not_subsets(self):
        self.package(); original = read(self.request['comparison']); normals = read(self.request['normalizations'])
        for defect in ('omitted', 'extra', 'duplicate'):
            with self.subTest(defect=defect):
                case, receipts = deepcopy(original), deepcopy(normals)
                if defect == 'omitted': case['anchors'].pop(); receipts.pop()
                else:
                    case['anchors'].append(deepcopy(case['anchors'][0])); receipts.append(deepcopy(receipts[0]))
                    if defect == 'extra':
                        catalog = read(self.request['catalog'])
                        extra, receipt = nuscenes.normalize_frame(
                            sample_token='f0-3', anchor_id='extra', ego_xy=[10, 20], weight=Fraction(1, 3),
                            base={'state': 'observed', 'value': [r for r in read(catalog['sources']['base']) if r['sample_token'] == 'f0-3']},
                            camera={'state': 'observed', 'value': [r for r in read(catalog['sources']['camera']) if r['sample_token'] == 'f0-3']},
                            source_sha256=receipts[0]['source_sha256'])
                        case['anchors'][-1] = extra; receipts[-1] = receipt
                for anchor, receipt in zip(case['anchors'], receipts):
                    anchor['weight'] = decision.wire(Fraction(1, len(case['anchors'])))
                    receipt['normalized_anchor_sha256'] = hashlib.sha256(decision.encoded(anchor)).hexdigest()
                replace(self.request, 'comparison', case); replace(self.request, 'normalizations', receipts)
                self.rejected('DUPLICATE_ID' if defect == 'duplicate' else 'BINDING_POPULATION')

    def test_duplicate_window_and_omitted_window_rejected(self):
        w = read(self.observation['window_report']); g = read(self.observation['geometry_report'])
        for report in (w, g): report['windows'].append(deepcopy(report['windows'][0]))
        replace(self.observation, 'window_report', w); g['inputs']['window_report'] = self.observation['window_report']
        replace(self.observation, 'geometry_report', g)
        self.rejected('OBS_BINDING', self.package)
        # A valid one-window package, with its capture union reduced consistently.
        for report in (w, g): report['windows'] = report['windows'][:1]
        tokens = {r['sample_data_token'] for r in g['windows'][0]['captures']}
        g['captures'] = {k: v for k, v in g['captures'].items() if k in tokens}
        replace(self.observation, 'window_report', w); g['inputs']['window_report'] = self.observation['window_report']
        replace(self.observation, 'geometry_report', g)
        self.package(); self.rejected('BINDING_POPULATION')

    def test_missing_and_other_nondelivered_states_are_preserved(self):
        inv = read(self.observation['inventory']); one, two, three, four, five = inv['assets'][:5]
        (self.root/'raw'/one['filename']).unlink()
        inv['assets'][1] = {'filename': two['filename'], 'state': 'unavailable', 'reason': 'not supplied'}
        inv['assets'].remove(three)
        (self.root/'raw'/four['filename']).write_bytes(b'corrupt')
        data = struct.pack('<5f', 1, 2, 3, 4, float('nan'))
        (self.root/'raw'/five['filename']).write_bytes(data)
        five.update(byte_size=len(data), sha256=hashlib.sha256(data).hexdigest())
        replace(self.observation, 'inventory', inv)
        w = read(self.observation['window_report']); w['inputs']['inventory'] = self.observation['inventory']
        rebind_window(self.observation, w)
        self.package(); report = binding.build(self.request)
        self.assertEqual(report['summary']['evidence_states'],
                         {'delivered': 65, 'missing': 1, 'unavailable': 1, 'not_listed': 1, 'invalid': 1, 'sensor_invalid': 1})
        self.assertEqual(len(report['captures']), 70)
        absent = [r for r in report['captures'] if r['source_content_check'] == 'not_delivered']
        self.assertEqual(len(absent), 5); self.assertTrue(all(r['delivered_source_body'] is None for r in absent))

    def test_withheld_not_checked_and_unavailable_geometry_remain_explicit(self):
        g = read(self.observation['geometry_report'])
        g['windows'][0]['captures'][0]['nominal_sensor_to_anchor_ego'] = {'state': 'unavailable', 'matrix': None}
        replace(self.observation, 'geometry_report', g)
        for code, state in [('OBS_JPEG_PROFILE', 'withheld'), ('WINDOW_DECODER_UNAVAILABLE', 'not_checked')]:
            with self.subTest(state=state):
                with patch.object(formats, 'camera', side_effect=decision.Invalid(code, 'fixture')):
                    self.package()
                report = binding.build(self.request)
                self.assertEqual(report['summary']['evidence_states'], {'delivered': 10, state: 60})
                m = json.loads((self.out/'manifest.json').read_bytes())
                self.assertEqual(m['windows'][0]['channels']['LIDAR_TOP']['captures'][0]['sensor_to_anchor_ego'],
                                 {'state': 'unavailable'})

    def test_forged_custody_mapping_is_not_used_as_the_join(self):
        self.package(); c = read(self.request['observation_custody']); c['windows'][0]['sample_token'] = 'f0-3'
        replace(self.request, 'observation_custody', c); self.rejected('BINDING_CUSTODY')

    def test_valid_package_cannot_change_inventory_availability(self):
        self.package(); m = json.loads((self.out/'manifest.json').read_bytes())
        row = m['captures'][0]; (self.out/row['evidence']['asset']['filename']).unlink()
        row['evidence'] = {'state': 'unavailable'}
        self.reseal(m); self.rejected('BINDING_AVAILABILITY')

    def test_missing_prediction_is_preserved_and_never_becomes_an_empty_output(self):
        self.package(); case = read(self.request['comparison']); normals = read(self.request['normalizations'])
        catalog = read(self.request['catalog'])
        anchor, receipt = nuscenes.normalize_frame(
            sample_token='f0-2', anchor_id='one', ego_xy=[10, 20], weight=Fraction(1, 2),
            base={'state': 'missing', 'reason': 'frame not supplied'},
            camera={'state': 'observed', 'value': [r for r in read(catalog['sources']['camera']) if r['sample_token'] == 'f0-2']},
            source_sha256=normals[0]['source_sha256'])
        case['anchors'][0] = anchor; normals[0] = receipt
        replace(self.request, 'comparison', case); replace(self.request, 'normalizations', normals)
        report = binding.build(self.request)
        self.assertEqual(report['comparison_output_states'][0], {'anchor_id': 'one', 'base': 'missing', 'additions': 'unknown'})
        self.assertFalse(report['decision_evaluated'])

    def test_normalization_role_and_missing_pose_remain_required(self):
        self.package(); original = read(self.request['normalizations'])
        n = deepcopy(original); n[0]['source_sha256']['camera'] = n[0]['source_sha256']['base']
        replace(self.request, 'normalizations', n); self.rejected('REFERENCE_BINDING')
        replace(self.request, 'normalizations', original)
        cat = read(self.request['catalog']); next(r for r in cat['anchors'] if r['sample_token'] == 'f0-2')['nominal_ego_xy'] = {'state': 'missing'}
        replace(self.request, 'catalog', cat)
        w = read(self.observation['window_report']); w['inputs']['catalog'] = self.request['catalog']
        rebind_window(self.observation, w)
        g = read(self.observation['geometry_report']); g['inputs']['catalog'] = self.request['catalog']
        replace(self.observation, 'geometry_report', g)
        self.package(); self.rejected('REFERENCE_POSE')

    def test_expected_seal_cannot_be_supplied_only_by_the_package(self):
        self.package(); self.request['package']['seal_sha256'] = 'f'*64
        self.rejected('BINDING_CUSTODY')

    def test_inputs_rehashed_after_use_and_runtime_change_rejected(self):
        self.package(); original = binding.asset_bindings
        def changed(*args):
            result = original(*args)
            path = Path(self.request['comparison']['path']); path.write_bytes(path.read_bytes()+b' ')
            return result
        with patch.object(binding, 'asset_bindings', changed): self.rejected('SOURCE_SIZE')
        path = Path(self.request['comparison']['path']); path.write_bytes(path.read_bytes()[:-1])
        with patch.object(binding, 'runtime', side_effect=[{'version': 1}, {'version': 2}]):
            self.rejected('BINDING_CODE_CHANGED')

    def test_closed_request_and_required_invalid_structure_fail_without_output(self):
        self.package(); original = deepcopy(self.request)
        for field, value, code in [('extra', True, 'BINDING_REQUEST'),
                                  ('normalizations', [], 'GEOMETRY_REQUEST')]:
            self.request = deepcopy(original); self.request[field] = value; self.rejected(code)
        self.request = original
        replace(self.request, 'normalizations', [None]); self.rejected('REFERENCE_BINDING')
        replace(self.request, 'normalizations', [True]); self.rejected('REFERENCE_BINDING')

    def test_atomic_private_output_strict_request_parsing_and_cli(self):
        self.package(); request = identity_file(self.root/'request.json', decision.encoded(self.request))
        output = self.root/'binding.private.json'
        argv = [sys.executable, '-B', '-m', 'tools.perception_binding', '--request', request['path'],
                '--request-sha256', request['sha256'], '--output', str(output)]
        run = subprocess.run(argv, capture_output=True)
        self.assertEqual(run.returncode, 0, run.stderr); self.assertEqual(run.stderr, b'')
        before = output.read_bytes(); summary = json.loads(run.stdout)
        self.assertEqual(summary['report_sha256'], hashlib.sha256(before).hexdigest())
        again = subprocess.run(argv, capture_output=True)
        self.assertEqual(again.returncode, 2); self.assertEqual(json.loads(again.stderr)['code'], 'OUTPUT_EXISTS')
        self.assertEqual(output.read_bytes(), before)
        self.rejected('BINDING_PRIVATE_OUTPUT', lambda: binding.run(request['path'], request['sha256'], self.out/'private.json'))
        self.assertFalse((self.out/'private.json').exists())
        for raw, code in [(b'{"x":1,"x":2}', 'DUPLICATE_KEY'), (b'{"x":NaN}', 'INVALID_NUMBER')]:
            bad = identity_file(self.root/'bad-request.json', raw)
            self.rejected(code, lambda: binding.run(bad['path'], bad['sha256'], self.root/'absent.json'))
            self.assertFalse((self.root/'absent.json').exists())


if __name__ == '__main__':
    unittest.main()
