"""Gate B check: one command, fail closed, machine-readable.

Gate A has a byte-bound launcher; Gate B has had a reconciliation check and a discipline. This is
the discipline as a command. It verifies, in order, and never weakens a check to pass:

  1. MANIFEST   validation/gate-b-replay-manifest.json validates structurally; every retained
                transcript it names exists and its SHA-256 equals the recorded digest.
  2. REPLAY     with --replay CLASS[,CLASS], every transcript of those replay classes is
                regenerated by its recorded command and compared byte for byte. Without --replay,
                every transcript is reported as not_replayed_here, a distinct state that is never
                counted as replicated. Classes: local_deterministic (inputs local and regenerable),
                network_cached (public files fetched at run time), heavy_inference (executes a
                pretrained detector on video). argv_unrecorded_historical rows are never replayed
                here and say so.
  3. REGISTER   the newest claim register validates and the reconciliation check passes.
  4. CUSTODY    every retained publisher record named by the custody record matches its digest.
  5. STYLE      no em dash in any live Markdown outside history/; every result document carries a
                Document ID, Version and Lifecycle status; every relative Markdown link resolves.

Exit 0 only when every check passes and no replay diverged. Exit 1 on any failure. Exit 2 on a
structural failure. The JSON report (--json PATH) lists every item with its state.
"""
import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys

MANIFEST = "validation/gate-b-replay-manifest.json"
CUSTODY = "evidence/public-data-custody-2026-09-06.json"
CLASSES = ("local_deterministic", "network_cached", "heavy_inference", "argv_unrecorded_historical")


def sha(p):
    return "sha256:" + hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--replay", default="", help="comma-separated replay classes to regenerate")
    ap.add_argument("--json", default="", help="write the machine-readable report here")
    ap.add_argument("--attacks", action="store_true", help="also run the attack suite (review instrument 3; several minutes)")
    a = ap.parse_args()
    replay = {c for c in a.replay.split(",") if c}
    unknown = replay - set(CLASSES)
    if unknown:
        print(f"STRUCTURAL FAILURE: unknown replay class {sorted(unknown)}"); return 2
    report = {"tool": "gate_b_check", "version": "0.1.0", "checks": [], "items": []}
    fails = 0

    def check(name, ok, detail=""):
        nonlocal fails
        report["checks"].append({"check": name, "state": "pass" if ok else "fail", "detail": detail})
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}{(': ' + detail) if detail else ''}")
        if not ok:
            fails += 1

    print("=" * 92); print("GATE B CHECK"); print("=" * 92)
    try:
        man = json.loads(pathlib.Path(MANIFEST).read_text(encoding="utf-8"))
        assert man["manifest_kind"] == "gate-b-replay-manifest" and isinstance(man["transcripts"], list)
        for row in man["transcripts"]:
            assert set(row) >= {"transcript", "sha256", "tool", "argv", "replay_class", "results"}, row
            assert row["replay_class"] in CLASSES, row["replay_class"]
    except Exception as e:  # noqa: BLE001
        print(f"STRUCTURAL FAILURE: manifest: {type(e).__name__}: {e}"); return 2

    # 1. manifest digests
    bad = []
    for row in man["transcripts"]:
        p = pathlib.Path(row["transcript"])
        state = "missing" if not p.exists() else ("digest_match" if sha(p) == row["sha256"] else "digest_mismatch")
        if state != "digest_match":
            bad.append(f"{row['transcript']}: {state}")
        report["items"].append({"transcript": row["transcript"], "digest_state": state, "replay_class": row["replay_class"], "replay_state": None})
    check("MANIFEST  every retained transcript exists with its recorded SHA-256", not bad, f"{len(man['transcripts'])} transcripts" + (f"; {bad}" if bad else ""))

    # 2. replay
    diverged, replicated, skipped = [], [], 0
    for row, item in zip(man["transcripts"], report["items"]):
        cls = row["replay_class"]
        if cls not in replay or cls == "argv_unrecorded_historical" or not row["argv"]:
            item["replay_state"] = "not_replayed_here" if cls != "argv_unrecorded_historical" else "argv_unrecorded_historical"
            skipped += 1
            continue
        try:
            out = subprocess.run(row["argv"], capture_output=True, timeout=row.get("timeout_s", 7200))
            text = out.stdout.decode("utf-8", errors="replace")
            if row.get("stderr_merged"):
                text = (out.stdout + out.stderr).decode("utf-8", errors="replace")
            text = "\n".join(l for l in text.splitlines() if not l.startswith("Warning: You are sending")) + ("\n" if text.endswith("\n") else "")
            same = "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest() == row["sha256"]
        except Exception as e:  # noqa: BLE001
            same = False; text = f"{type(e).__name__}: {e}"
        item["replay_state"] = "replicated" if same else "diverged"
        (replicated if same else diverged).append(row["transcript"])
    check("REPLAY    every replayed transcript is byte-identical", not diverged,
          f"{len(replicated)} replicated, {skipped} not replayed here" + (f"; diverged: {diverged}" if diverged else ""))

    # 3. register and reconciliation
    rec = subprocess.run([sys.executable, "tools/measure/check_claim_reconciliation.py"], capture_output=True, text=True)
    check("REGISTER  newest register validates and reconciliation passes", rec.returncode == 0, rec.stdout.strip().splitlines()[-2].strip() if rec.stdout else rec.stderr[:200])

    # 4. custody digests
    cus = json.loads(pathlib.Path(CUSTODY).read_text(encoding="utf-8"))
    cbad = []
    for s in cus["sources"]:
        r = s.get("retained_record")
        if r and sha(r["path"]) != r["sha256"]:
            cbad.append(r["path"])
        for f in s.get("payload_in_public_git", []):
            if hashlib.md5(pathlib.Path(f["path"]).read_bytes()).hexdigest() != f["md5"]:
                cbad.append(f["path"])
    check("CUSTODY   retained publisher records and committed payloads match their digests", not cbad, str(cbad) if cbad else f"{len(cus['sources'])} sources")

    # 5. style
    live = [p for p in pathlib.Path(".").rglob("*.md") if not str(p).startswith("history/") and ".git" not in p.parts and "node_modules" not in p.parts]
    emd = [str(p) for p in live if "—" in p.read_text(encoding="utf-8", errors="replace")]
    check("STYLE     no em dash in live Markdown", not emd, str(emd) if emd else f"{len(live)} files")
    missing_hdr, broken = [], []
    for row in man["transcripts"]:
        for doc in row["results"]:
            t = pathlib.Path(doc).read_text(encoding="utf-8")
            if not (re.search(r"^Document ID: `", t, re.M) and re.search(r"^Version: `", t, re.M) and re.search(r"^Lifecycle status: `", t, re.M)):
                missing_hdr.append(doc)
    for p in live:
        t = p.read_text(encoding="utf-8", errors="replace")
        for l in re.findall(r"\]\(([^)#\s]+\.md)\)", t):
            if not l.startswith("http") and not (p.parent / l).exists():
                broken.append(f"{p}:{l}")
    check("STYLE     every result document carries Document ID, Version, Lifecycle status", not missing_hdr, str(missing_hdr) if missing_hdr else "")
    check("STYLE     every relative Markdown link resolves", not broken, str(broken[:6]) if broken else "")

    # 6. review instrument: every number in every result document bound to retained bytes
    rb = subprocess.run([sys.executable, "tools/measure/review_number_binding.py"], capture_output=True, text=True)
    last = [l for l in rb.stdout.splitlines() if l.strip().startswith("RESULT:")]
    check("REVIEW    every number in every result document is bound to retained bytes", rb.returncode == 0, last[-1].strip() if last else rb.stderr[:200])

    rc = subprocess.run([sys.executable, "tools/measure/review_register_coverage.py"], capture_output=True, text=True)
    last = [l for l in rc.stdout.splitlines() if l.strip().startswith("RESULT:")]
    check("REVIEW    the register and the result documents describe the same program", rc.returncode == 0, last[-1].strip() if last else rc.stderr[:200])

    if a.attacks:
        # the attack suite needs the analysis environment (scikit-learn); use the interpreter the
        # manifest records for the local_deterministic rows, never the check's own interpreter
        interp = next((row["argv"][0] for row in man["transcripts"] if row["replay_class"] == "local_deterministic" and row["argv"]), sys.executable)
        ra = subprocess.run([interp, "tools/measure/review_attacks.py"], capture_output=True, text=True)
        last = [l for l in ra.stdout.splitlines() if l.strip().startswith("RESULT:")]
        check("REVIEW    the attack suite: every attack with a stated criterion fails to break its result", ra.returncode == 0, last[-1].strip() if last else ra.stderr[:200])
    else:
        report["checks"].append({"check": "REVIEW    attack suite", "state": "not_run_here", "detail": "pass --attacks to run"})
        print("  [SKIP] REVIEW    attack suite not run here (pass --attacks); its last retained transcript is under evidence/")

    report["result"] = "pass" if fails == 0 else "fail"
    print(f"\n  RESULT: {report['result'].upper()}  ({fails} failing check(s))")
    if a.json:
        pathlib.Path(a.json).write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return 0 if fails == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
