"""Critical contract and forged-transcript controls, version 0.1.0."""
from copy import deepcopy
from fractions import Fraction as F
import json
from methods import validate, probabilities, validate_probabilities, logical, factor
from check import Reference, VerificationError

def main():
    base={'id':'control','version':'0.1.0','threshold':'0','purpose':'control only',
          'units':[{'id':'a','weight':'1/2','lower':'1','upper':'1','proxy':'-1','status':'observed','cluster':'x'},
                   {'id':'b','weight':'1/2','lower':'-1','upper':'-1','proxy':'1','status':'observed','cluster':'x'}]}
    checks=[]
    def reject(name,call,reason):
        try:call()
        except ValueError as err:
            assert str(err)==reason,(name,str(err),reason)
        else:raise AssertionError(name+' accepted')
        checks.append({'id':name,'passed':True,'expected_rejection':reason})
    def changed(change):
        p=deepcopy(base);change(p);return p
    reject('unknown_population_field',lambda:validate(changed(lambda p:p.update(extra=True))),'population_properties')
    reject('duplicate_identity',lambda:validate(changed(lambda p:p['units'][1].update(id='a'))),'population_membership')
    reject('negative_weight',lambda:validate(changed(lambda p:p['units'][0].update(weight='-1/2'))),'unit_range')
    reject('weight_mass',lambda:validate(changed(lambda p:p['units'][0].update(weight='1/3'))),'weight_sum')
    reject('float_threshold',lambda:validate(changed(lambda p:p.update(threshold=0.0))),'rational_string_required')
    reject('noncanonical_fraction',lambda:validate(changed(lambda p:p.update(threshold='0/2'))),'canonical_rational_required')
    reject('inverted_interval',lambda:validate(changed(lambda p:p['units'][0].update(lower='1',upper='-1'))),'unit_range')
    reject('unknown_status',lambda:validate(changed(lambda p:p['units'][0].update(status='normal'))),'unknown_observation_status')
    reject('missing_coerced_zero',lambda:validate(changed(lambda p:p['units'][0].update(status='missing',lower='0',upper='0'))),'unavailable_must_retain_full_interval')
    reject('zero_sampling_support',lambda:validate_probabilities({0:F(1),1:F(0)},[0,1]),'sampling_support_or_mass')
    reject('wrong_sampling_mass',lambda:validate_probabilities({0:F(1),1:F(1)},[0,1]),'sampling_support_or_mass')
    reject('absent_sampling_member',lambda:validate_probabilities({0:F(1)},[0,1]),'sampling_support_or_mass')
    ref=Reference(base);valid=ref.expected('proxy_cv','01');ref.verify_row(valid)
    for key,value in [('probability','1'),('e_lower_at_stop','999'),('stat_decision','supported'),('stat_stop','0'),('lower_ever_crossed','1')]:
        forged={**valid,key:value}
        reject('forged_'+key,lambda f=forged:ref.verify_row(f),'path_'+key)
    reject('repeated_query',lambda:ref.expected('uniform','00'),'order_membership')
    reject('changed_threshold_reuse',lambda:Reference(changed(lambda p:p.update(threshold='1'))).verify_row(valid),'path_exact_stop')
    # Directional support bound is tested on values not generated by the study producer.
    for cv in (False,True):
        weights=[F(1,3),F(2,3)];proxy=[F(0),F(1)];q={0:F(999,1000),1:F(1,1000)}
        for i in q:
            for x in (F(0),F(1)):
                assert factor(weights,proxy,{},(0,1),q,i,x,F(1,2),cv)>=0
    assert logical(base,{0,1})[0]=='excluded'
    assert logical(base,set())[0]=='unresolved'
    checks.append({'id':'support_extremes_and_strict_tie','passed':True})
    print(json.dumps({'document_id':'reiyah.sequential-audit.controls','version':'0.1.0','passed':True,'checks':checks},indent=2))

if __name__=='__main__':main()
